services:
  auth-backend:
    container_name: safiro
    restart: always
    volumes:
      - static_files:/home/app/static
    build:
      context: .
      dockerfile: dockerfile/prod/Dockerfile
    ports:
      - "8000:8000"
    expose:
      - 8000
    env_file: ".env"

  nginx:
    container_name: safiro_nginx
    restart: always
    build:
      context: .
      dockerfile: dockerfile/prod/nginx/Dockerfile
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - static_files:/var/www/static
      - letsencrypt_etc:/etc/letsencrypt
      - letsencrypt_var_lib:/var/lib/letsencrypt
    depends_on:
      - auth-backend

  redis:
    container_name: safiro_redis
    image: docker.arvancloud.ir/redis:8.2-alpine
    command: redis-server --save 60 1 --loglevel warning
    expose:
      - 6379
    ports:
      - "6379:6379"

  certbot:
    container_name: safiro_certbot
    image: docker.arvancloud.ir/certbot/certbot
    restart: always
    volumes:
      - letsencrypt_etc:/etc/letsencrypt
      - letsencrypt_var_lib:/var/lib/letsencrypt
      - certbot_www:/var/www/certbot
    command: >
      certonly --standalone
      -d api.safiro.ir
      -d flower.safiro.ir
      -d phero.safiro.ir
      -d pgadmin.safiro.ir
      -d pannel.safiro.ir
      -d sentry.safiro.ir
      -d log.safiro.ir
      -d monitor.safiro.ir
      -d grafana.safiro.ir
      --email mysum325g@gmail.com
      --agree-tos
      --non-interactive

  db:
    container_name: safiro_postgres
    env_file: "postdb.env"
    restart: always
    image: docker.arvancloud.ir/postgres:17-alpine
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data

volumes:
  postgres_volume:
  static_files:
  letsencrypt_etc:
  letsencrypt_var_lib:
  certbot_www: